---
- hosts: hostserver
  become: true
  become_user: root
  vars:
   repo_path: https://github.com/Sindhu-Mano/project1
   dest_path: /tmp/gitrepo
  tasks:
  - name: Install multiple packages on host server
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: Start the docker service
    service: name=docker state=started
  - name: Clone the repo to HostServer
    git: repo={{repo_path}} dest={{dest_path}}
  - name: Copy the build in the destination
    copy: src=/var/lib/jenkins/workspace/projectstatement1/target/addressbook.war dest={{dest_path}}
  - name: Build Dockerfile
    command: chdir={{dest_path}} docker build -t myimage1 .
  - name: Run the image to deploy app in container
    command: docker run -d -P myimage1
